# Generated by Django 6.0.4 on 2026-05-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("quantity", models.IntegerField()),
                ("revenue", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sale_date", models.DateField()),
            ],
        ),
    ]
