# Generated by Django 6.0.4 on 2026-05-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_queryhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="queryhistory",
            name="sql_query",
            field=models.TextField(blank=True, default=""),
        ),
    ]
