# Generated by Django 6.0.4 on 2026-05-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_queryhistory_sql_query"),
    ]

    operations = [
        migrations.AddField(
            model_name="queryhistory",
            name="session_id",
            field=models.CharField(db_index=True, default="default", max_length=255),
        ),
    ]
