# Generated by Django 6.0.4 on 2026-05-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_queryhistory_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="queryhistory",
            name="execution_time",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
