# Generated by Django 6.0.4 on 2026-05-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0005_queryhistory_execution_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="queryhistory",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
