# Generated by Django 6.0.4 on 2026-05-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0006_queryhistory_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="queryhistory",
            name="estimated_cost",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="queryhistory",
            name="input_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="queryhistory",
            name="output_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
