# Generated by Django 6.0.4 on 2026-05-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0007_queryhistory_estimated_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="queryhistory",
            name="has_data",
            field=models.BooleanField(default=False),
        ),
    ]
