# Generated by Django 6.0.4 on 2026-05-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0008_queryhistory_has_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("query", models.TextField()),
                ("sql_command", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
