# Generated by Django 6.0.4 on 2026-05-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0009_savedprompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="queryhistory",
            name="task_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
