# Generated by Django 6.0.4 on 2026-05-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0010_queryhistory_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedprompt",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="savedprompt",
            name="sql_command",
            field=models.TextField(unique=True),
        ),
    ]
