# Generated by Django 6.0.4 on 2026-05-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0013_queryhistory_result_blocks"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Sale",
        ),
        migrations.AddField(
            model_name="queryhistory",
            name="thinking_steps",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="queryhistory",
            name="thinking_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
