# Generated by Django 6.0.4 on 2026-05-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0015_runwaretasklog"),
    ]

    operations = [
        migrations.AddField(
            model_name="runwaretasklog",
            name="raw_response_text",
            field=models.TextField(
                blank=True,
                help_text="Full raw text output from the LLM before JSON parsing.",
                null=True,
            ),
        ),
    ]
